-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 00:15:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oauth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oauth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oauth` DEFAULT CHARACTER SET utf8 ;
USE `oauth` ;

-- -----------------------------------------------------
-- Table `oauth`.`system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`system` ;

CREATE TABLE IF NOT EXISTS `oauth`.`system` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `system_code` VARCHAR(45) NOT NULL,
    `secret` VARCHAR(255) NOT NULL,
    `desc` VARCHAR(255) NULL,
    `enable` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `system_code_UNIQUE` (`system_code` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`account` ;

CREATE TABLE IF NOT EXISTS `oauth`.`account` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `system_id` INT NOT NULL,
                                                 `auth_code` VARCHAR(45) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `enable` TINYINT(1) NOT NULL DEFAULT 1,
    `locked` TINYINT(1) NOT NULL DEFAULT 0,
    `expired` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    UNIQUE INDEX `auth_code_UNIQUE` (`auth_code` ASC) VISIBLE,
    INDEX `account_sys_idx` (`system_id` ASC) VISIBLE,
    INDEX `multi_idx` (`system_id` ASC, `username` ASC, `email` ASC, `auth_code` ASC) VISIBLE,
    CONSTRAINT `account_sys`
    FOREIGN KEY (`system_id`)
    REFERENCES `oauth`.`system` (`id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`role` ;

CREATE TABLE IF NOT EXISTS `oauth`.`role` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `role_name` VARCHAR(45) NOT NULL,
    `desc` VARCHAR(255) NULL,
    `enable` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`account_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`account_roles` ;

CREATE TABLE IF NOT EXISTS `oauth`.`account_roles` (
                                                       `account_id` INT NOT NULL,
                                                       `role_id` INT NOT NULL,
                                                       `enable` TINYINT(1) NOT NULL DEFAULT 1,
    INDEX `role_accr_idx` (`role_id` ASC) VISIBLE,
    PRIMARY KEY (`account_id`, `role_id`),
    CONSTRAINT `acc_accr`
    FOREIGN KEY (`account_id`)
    REFERENCES `oauth`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `role_accr`
    FOREIGN KEY (`role_id`)
    REFERENCES `oauth`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`resource_servive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`resource_servive` ;

CREATE TABLE IF NOT EXISTS `oauth`.`resource_servive` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `service_name` VARCHAR(45) NOT NULL,
    `desc` VARCHAR(255) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `service_name_UNIQUE` (`service_name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`scope`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`scope` ;

CREATE TABLE IF NOT EXISTS `oauth`.`scope` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `resouce_id` INT NOT NULL,
                                               `scope` VARCHAR(100) NOT NULL,
    `enable` TINYINT(1) NOT NULL DEFAULT 0,
    `desc` VARCHAR(255) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `scope_UNIQUE` (`scope` ASC) VISIBLE,
    INDEX `resource_scope_idx` (`resouce_id` ASC) VISIBLE,
    CONSTRAINT `resource_scope`
    FOREIGN KEY (`resouce_id`)
    REFERENCES `oauth`.`resource_servive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`account_scopes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`account_scopes` ;

CREATE TABLE IF NOT EXISTS `oauth`.`account_scopes` (
                                                        `account_id` INT NOT NULL,
                                                        `scope_id` INT NOT NULL,
                                                        `enble` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`account_id`, `scope_id`),
    INDEX `accs_scop_idx` (`scope_id` ASC) VISIBLE,
    CONSTRAINT `acc_accs`
    FOREIGN KEY (`account_id`)
    REFERENCES `oauth`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `accs_scop`
    FOREIGN KEY (`scope_id`)
    REFERENCES `oauth`.`scope` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`client` ;

CREATE TABLE IF NOT EXISTS `oauth`.`client` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `client_id` VARCHAR(255) NOT NULL,
    `client_name` VARCHAR(45) NOT NULL,
    `client_secret` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`resource_service_scope`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`resource_service_scope` ;

CREATE TABLE IF NOT EXISTS `oauth`.`resource_service_scope` (
                                                                `resource_id` INT NOT NULL,
                                                                `scope_id` INT NOT NULL,
                                                                `enable` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`resource_id`, `scope_id`),
    INDEX `rss_s_idx` (`scope_id` ASC) VISIBLE,
    CONSTRAINT `rss_rs`
    FOREIGN KEY (`resource_id`)
    REFERENCES `oauth`.`resource_servive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `rss_s`
    FOREIGN KEY (`scope_id`)
    REFERENCES `oauth`.`scope` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`client_redirect_urls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`client_redirect_urls` ;

CREATE TABLE IF NOT EXISTS `oauth`.`client_redirect_urls` (
                                                              `id` INT NOT NULL AUTO_INCREMENT,
                                                              `client_id` INT NOT NULL,
                                                              `url` VARCHAR(1000) NOT NULL,
    `enable` TINYINT(1) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `client_url_idx` (`client_id` ASC) VISIBLE,
    CONSTRAINT `client_url`
    FOREIGN KEY (`client_id`)
    REFERENCES `oauth`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`role_default_scopes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`role_default_scopes` ;

CREATE TABLE IF NOT EXISTS `oauth`.`role_default_scopes` (
                                                             `role_id` INT NOT NULL,
                                                             `scope_id` INT NOT NULL,
                                                             `enabled` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`role_id`, `scope_id`),
    INDEX `rds_s_idx` (`scope_id` ASC) VISIBLE,
    CONSTRAINT `rds_r`
    FOREIGN KEY (`role_id`)
    REFERENCES `oauth`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `rds_s`
    FOREIGN KEY (`scope_id`)
    REFERENCES `oauth`.`scope` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`.`system_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth`.`system_settings` ;

CREATE TABLE IF NOT EXISTS `oauth`.`system_settings` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `key` VARCHAR(45) NOT NULL,
    `value` VARCHAR(3000) NOT NULL,
    `memo` VARCHAR(100) NULL,
    `json_data` JSON NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;